server:
  port: 8082

spring:
  application:
    name: ms-usuarios

  datasource:
    url: jdbc:mysql://localhost:3308/db_usuarios?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: vet_user
    password: vet_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true